version: "3"
services:
  app:
    container_name: arbitrage_backend
    build: .
    ports:
      - 8000:8000
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - arbitrage-postgres
    networks:
      - arbitrage

  arbitrage-postgres:
    image: postgres:latest
    container_name: arbitrage_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - arbitrage

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - arbitrage-postgres
    ports:
      - "5050:80"
    networks:
      - arbitrage
    restart: unless-stopped

volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  arbitrage:
    driver: bridge
